name: Deploy to server

on:
  pull_request:
    branches: [ main ]

jobs:
  Deploy-to-Server:
    runs-on: ubuntu-latest
    steps:
      - name: copy file via ssh
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_KEY }}
          port: ${{ secrets.SERVER_PORT }}
          source: "index.html"
          target: ${{ secrets.SERVER_PATH }}